<?php

namespace Typecho;

class MimeTypes
{
    private const TYPES = [
        'doc'      => 'application/msword',
        'dot'      => 'application/msword',
        'docx'     => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'bin'      => 'application/octet-stream',
        'ogg'      => 'application/ogg',
        'oga'      => 'audio/ogg',
        'ogv'      => 'video/ogg',
        'pdf'      => 'application/pdf',
        'ps'       => 'application/postscript',
        'ai'       => 'application/postscript',
        'eps'      => 'application/postscript',
        'rtf'      => 'text/rtf',
        'xhtml'    => 'application/xhtml+xml',
        'zip'      => 'application/zip',
        'xls'      => 'application/vnd.ms-excel',
        'xlsx'     => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'ppt'      => 'application/vnd.ms-powerpoint',
        'pptx'     => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'tgz'      => 'application/gzip',
        'gz'       => 'application/gzip',
        'phtml'    => 'application/x-httpd-php',
        'pht'      => 'application/x-httpd-php',
        'php'      => 'application/x-httpd-php',
        'phps'     => 'application/x-httpd-php-source',
        'php3'     => 'application/x-httpd-php3',
        'php4'     => 'application/x-httpd-php4',
        'php5'     => 'application/x-httpd-php5',
        'php6'     => 'application/x-httpd-php6',
        'php7'     => 'application/x-httpd-php',
        'php8'     => 'application/x-httpd-php',
        'phar'     => 'application/x-httpd-php',
        'shtml'    => 'text/x-server-parsed-html',
        'mpeg'     => 'video/mpeg',
        'mpg'      => 'video/mpeg',
        'qt'       => 'video/quicktime',
        'mov'      => 'video/quicktime',
        'avi'      => 'video/x-msvideo',
        'wmv'      => 'video/x-ms-wmv',
        'wma'      => 'audio/x-ms-wma',
        'flv'      => 'video/x-flv',
        'rm'       => 'application/vnd.rn-realmedia',
        'rmvb'     => 'application/vnd.rn-realmedia-vbr',
        'rar'      => 'application/x-rar-compressed',
        'cab'      => 'application/vnd.ms-cab-compressed',
        'webp'     => 'image/webp',
        'jpg'      => 'image/jpeg',
        'jpeg'     => 'image/jpeg',
        'png'      => 'image/png',
        'gif'      => 'image/gif',
        'bmp'      => 'image/bmp',
        'tif'      => 'image/tiff',
        'tiff'     => 'image/tiff',
        'avif'     => 'image/avif',
        'svg'      => 'image/svg+xml',
        'txt'      => 'text/plain',
        'css'      => 'text/css',
        'js'       => 'application/javascript',
        'json'     => 'application/json',
        'xml'      => 'application/xml',
        'csv'      => 'text/csv',
        'mp3'      => 'audio/mpeg',
        'wav'      => 'audio/wav',
        'mp4'      => 'video/mp4',
        'webm'     => 'video/webm',
        'mkv'      => 'video/x-matroska',
    ];

    public static function get(): array
    {
        return self::TYPES;
    }
}
